In [1]:
import torch

In [2]:
print(torch.__version__)

1.4.0


In [3]:
torch.get_default_dtype()

torch.float32

In [5]:
torch.set_default_dtype(torch.float64)

In [6]:
torch.get_default_dtype()

torch.float64

In [7]:
torch.set_default_dtype(torch.float32)

In [8]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
torch.is_tensor(tensor_arr)

True

In [10]:
#printing the number of elements
torch.numel(tensor_arr)

6

In [11]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[1.0561e-38, 8.4490e-39],
        [9.2755e-39, 1.0745e-38]])

In [12]:
tensor_initialized = torch.rand(2,2)
tensor_initialized

tensor([[0.1845, 0.5065],
        [0.8770, 0.4085]])

In [13]:
tensor_fill = torch.full([2,4], fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [14]:
tensors_of_ones = torch.ones([2,4], dtype=torch.int32)
tensors_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [15]:
tensors_of_zeroes = torch.zeros([2,4], dtype= torch.int32)
tensors_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [16]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
#Finding nonzero elements in a matrix
nonzero = torch.nonzero(tensor_eye)
nonzero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [18]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.4189, 0.4423, 0.4374],
        [0.8106, 0.0964, 0.2566]])

In [19]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [20]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [21]:
new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [22]:
#Generating elements between two numbers with given numbers as size
x = torch.linspace(start=0, end=10, steps=10)
x

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [23]:
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.0000, 1.1111, 2.2222, 3.3333]),
 tensor([4.4444, 5.5556, 6.6667, 7.7778]),
 tensor([ 8.8889, 10.0000]))

In [27]:
random_tensor = torch.Tensor([[10, 8 , 30], [40, 5, 6], [12, 2 , 100]])
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [28]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [29]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [30]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

In [31]:
#Convert the elements into positive
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

In [32]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))

In [33]:
rand1

tensor([[0.8148, 0.3238, 0.7196],
        [0.0079, 0.2349, 0.4068]])

In [34]:
rand2

tensor([[0.6499, 0.3191, 0.9551],
        [1.6536, 0.5791, 0.0662]])

In [36]:
add1 = rand1 + rand2
add1

tensor([[1.4647, 0.6429, 1.6747],
        [1.6615, 0.8140, 0.4731]])

In [38]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.4647, 0.6429, 1.6747],
        [1.6615, 0.8140, 0.4731]])

In [37]:
sub1 = rand1 - rand2
sub1

tensor([[ 0.1649,  0.0047, -0.2355],
        [-1.6456, -0.3442,  0.3406]])

In [39]:
sub2 = torch.sub(rand1, rand2)
sub2

tensor([[ 0.1649,  0.0047, -0.2355],
        [-1.6456, -0.3442,  0.3406]])

In [40]:
tensor_mul = torch.mul(rand1, rand2)
tensor_mul

tensor([[0.5296, 0.1033, 0.6873],
        [0.0131, 0.1360, 0.0269]])

In [41]:
tensor = torch.Tensor([[-1, -2,-3], [1, 2, 3]])
tensor

tensor([[-1., -2., -3.],
        [ 1.,  2.,  3.]])

In [42]:
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [43]:
torch.cuda.is_available()

False