In [1]:
import torch

In [2]:
# Initialize Variables

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

In [3]:
print(x*y)

tensor([10.,  3.])


In [4]:
x

tensor([5., 3.])

In [5]:
a = torch.zeros([2,5])
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
a.shape

torch.Size([2, 5])

In [7]:
b = torch.rand([2,5])
b

tensor([[0.8144, 0.7036, 0.0956, 0.3528, 0.7762],
        [0.2509, 0.9544, 0.0299, 0.1114, 0.1175]])

In [8]:
 b.view([1,10])

tensor([[0.8144, 0.7036, 0.0956, 0.3528, 0.7762, 0.2509, 0.9544, 0.0299, 0.1114,
         0.1175]])